import type { HousingDetails } from "@/lib/housing";
import type {
  ItemCondition,
  ListingIntent,
  ListingType,
  NegotiationMode,
} from "@/lib/listing-taxonomy";

export type Listing = {
  id: string;
  sellerId?: string;
  intent: ListingIntent;
  type: ListingType;
  category: string;
  focus?: string;
  itemCondition?: ItemCondition;
  negotiationMode: NegotiationMode;
  imageUrl?: string;
  galleryUrls?: string[];
  locationNote?: string;
  housingDetails?: HousingDetails;
  title: string;
  price: number;
  priceUnit?: string;
  campus: string;
  sellerName: string;
  sellerCourse: string;
  rating: number;
  deliveryMode: string;
  featured: boolean;
  description: string;
  tags: string[];
};

export const mockListings: Listing[] = [
  {
    id: "housing-republica-cruz",
    sellerId: "marina-costa",
    intent: "offer",
    type: "product",
    category: "Moradia",
    focus: "Vaga em republica",
    negotiationMode: "fixed",
    title: "Vaga feminina em republica perto da biblioteca",
    price: 650,
    priceUnit: "mes",
    campus: "Cruz das Almas",
    locationNote: "Rua da biblioteca, 8 min do campus",
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
    ],
    housingDetails: {
      listingKind: "republica_spot",
      totalRent: 2600,
      splitRent: 650,
      availableSlots: 1,
      totalResidents: 4,
      bedrooms: 3,
      bathrooms: 2,
      garageSpots: 1,
      furnished: true,
      acceptsPets: false,
      internetIncluded: true,
      waterIncluded: true,
      electricityIncluded: false,
      genderPreference: "women",
      paymentDay: 5,
      availableFrom: "2026-04-01",
      obligations: [
        "cleaning_scale",
        "bills_on_time",
        "quiet_hours",
        "respect_shared_spaces",
      ],
    },
    sellerName: "Marina Costa",
    sellerCourse: "Nutricao",
    rating: 4.8,
    deliveryMode: "Visita combinada e entrada a partir de abril",
    featured: true,
    description:
      "Quarto mobiliado em republica organizada, com internet, agua inclusa e rotina tranquila durante a semana.",
    tags: ["moradia", "republica", "vaga feminina", "aluguel dividido"],
  },
  {
    id: "housing-quarto-saj",
    sellerId: "lucas-santana",
    intent: "offer",
    type: "product",
    category: "Moradia",
    focus: "Quarto individual",
    negotiationMode: "negotiable",
    title: "Quarto individual com garagem em apartamento estudantil",
    price: 890,
    priceUnit: "mes",
    campus: "Santo Antonio de Jesus",
    locationNote: "Apartamento a 12 min do campus",
    imageUrl:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
    housingDetails: {
      listingKind: "private_room",
      totalRent: 1780,
      splitRent: 890,
      availableSlots: 1,
      totalResidents: 2,
      bedrooms: 2,
      bathrooms: 2,
      garageSpots: 1,
      furnished: true,
      acceptsPets: true,
      internetIncluded: true,
      waterIncluded: false,
      electricityIncluded: false,
      genderPreference: "any",
      paymentDay: 10,
      availableFrom: "2026-03-28",
      obligations: ["bills_on_time", "visits_agreed", "respect_shared_spaces"],
    },
    sellerName: "Lucas Santana",
    sellerCourse: "Zootecnia",
    rating: 4.6,
    deliveryMode: "Visita no fim da tarde e entrada rapida",
    featured: false,
    description:
      "Apartamento silencioso, com vaga de garagem e quarto ja com cama, armario e mesa de estudos.",
    tags: ["moradia", "quarto individual", "garagem", "pet friendly"],
  },
  {
    id: "housing-demanda-amargosa",
    sellerId: "sofia-lima",
    intent: "request",
    type: "product",
    category: "Moradia",
    focus: "Vaga em republica",
    negotiationMode: "negotiable",
    title: "Procuro vaga em republica feminina com contas organizadas",
    price: 700,
    priceUnit: "mes",
    campus: "Amargosa",
    locationNote: "Entre campus e centro",
    housingDetails: {
      listingKind: "republica_spot",
      splitRent: 700,
      availableSlots: 1,
      totalResidents: 4,
      furnished: true,
      acceptsPets: false,
      internetIncluded: true,
      waterIncluded: true,
      electricityIncluded: false,
      genderPreference: "women",
      paymentDay: 5,
      availableFrom: "2026-04-10",
      obligations: ["cleaning_scale", "bills_on_time", "quiet_hours"],
    },
    sellerName: "Sofia Lima",
    sellerCourse: "Bacharelado Interdisciplinar em Saude",
    rating: 4.7,
    deliveryMode: "Posso visitar no turno da tarde",
    featured: true,
    description:
      "Quero entrar em casa tranquila, com rotina de limpeza definida e pagamento sem atraso.",
    tags: ["demanda", "moradia", "republica feminina", "quarto"],
  },
  {
    id: "svc-calculo",
    sellerId: "ana-beatriz",
    intent: "offer",
    type: "service",
    category: "Aulas e monitoria",
    focus: "Grupo - Universitario",
    negotiationMode: "fixed",
    title: "Grupo de estudos de Calculo I",
    price: 35,
    priceUnit: "hora",
    campus: "Cruz das Almas",
    locationNote: "Biblioteca central",
    sellerName: "Ana Beatriz",
    sellerCourse: "Engenharia Agronomica",
    rating: 4.9,
    deliveryMode: "Presencial ou videochamada",
    featured: true,
    description:
      "Aulas objetivas para prova, listas e revisao de fundamentos com material resumido.",
    tags: ["matematica", "revisao", "provas"],
  },
  {
    id: "svc-design",
    sellerId: "luiz-felipe",
    intent: "offer",
    type: "service",
    category: "Design",
    focus: "Apresentacao",
    negotiationMode: "negotiable",
    title: "Design de apresentacoes e pitch decks",
    price: 120,
    priceUnit: "projeto",
    campus: "Feira de Santana",
    locationNote: "Online ou campus",
    sellerName: "Luiz Felipe",
    sellerCourse: "Publicidade",
    rating: 4.8,
    deliveryMode: "Entrega digital",
    featured: false,
    description:
      "Slides com identidade visual, narrativa e adaptacao para seminarios, extensao e defesa.",
    tags: ["apresentacao", "canva", "pitch"],
  },
  {
    id: "prd-airfryer",
    sellerId: "marina-costa",
    intent: "offer",
    type: "product",
    category: "Eletronicos",
    focus: "Cozinha",
    itemCondition: "used",
    negotiationMode: "fixed",
    title: "Air fryer seminova Mondial 4L",
    price: 220,
    campus: "Santo Antonio de Jesus",
    locationNote: "Apartamento perto do campus",
    sellerName: "Marina Costa",
    sellerCourse: "Nutricao",
    rating: 4.7,
    deliveryMode: "Retirada no campus",
    featured: false,
    description:
      "Pouco uso, funcionando perfeitamente e ideal para apartamento estudantil.",
    tags: ["cozinha", "seminovo", "retirada"],
  },
  {
    id: "prd-livros-fisica",
    sellerId: "rafael-nunes",
    intent: "offer",
    type: "product",
    category: "Livros",
    focus: "Academico",
    itemCondition: "used",
    negotiationMode: "negotiable",
    title: "Kit com livros de Fisica II",
    price: 85,
    campus: "Amargosa",
    locationNote: "Bloco de Fisica",
    sellerName: "Rafael Nunes",
    sellerCourse: "Licenciatura em Fisica",
    rating: 4.6,
    deliveryMode: "Entrega combinada",
    featured: false,
    description:
      "Colecao usada com anotacoes leves, ideal para quem quer economizar no semestre.",
    tags: ["livros", "fisica", "seminovo"],
  },
  {
    id: "svc-foto",
    sellerId: "joao-victor",
    intent: "offer",
    type: "service",
    category: "Audiovisual",
    focus: "Fotografia",
    negotiationMode: "fixed",
    title: "Cobertura fotografica para eventos academicos",
    price: 180,
    priceUnit: "evento",
    campus: "Cachoeira",
    locationNote: "Campus e centro historico",
    sellerName: "Joao Victor",
    sellerCourse: "Cinema e Audiovisual",
    rating: 4.9,
    deliveryMode: "Presencial",
    featured: true,
    description:
      "Ensaios, cobertura de palestras e conteudo rapido para redes de atleticas e centros academicos.",
    tags: ["foto", "evento", "midias sociais"],
  },
  {
    id: "prd-notebook",
    sellerId: "camila-rocha",
    intent: "offer",
    type: "product",
    category: "Tecnologia",
    focus: "Estudos",
    itemCondition: "used",
    negotiationMode: "counter_offer",
    title: "Notebook Dell Inspiron 15",
    price: 1850,
    campus: "Cruz das Almas",
    locationNote: "Pavilhao 2",
    sellerName: "Camila Rocha",
    sellerCourse: "Ciencia da Computacao",
    rating: 4.8,
    deliveryMode: "Retirada ou entrega local",
    featured: true,
    description:
      "Equipamento em bom estado, SSD instalado e bateria com autonomia para aulas e pesquisa.",
    tags: ["notebook", "estudos", "ssd"],
  },
  {
    id: "svc-transporte",
    sellerId: "pedro-henrique",
    intent: "offer",
    type: "service",
    category: "Transporte comunitario",
    focus: "Grupo por horario",
    negotiationMode: "counter_offer",
    title: "Grupo fixo campus - rodoviaria",
    price: 18,
    priceUnit: "corrida",
    campus: "Santo Amaro",
    locationNote: "Saida da rodoviaria",
    sellerName: "Pedro Henrique",
    sellerCourse: "Interdisciplinar em Energia",
    rating: 4.5,
    deliveryMode: "Agendamento por horario",
    featured: false,
    description:
      "Rotas frequentes em horarios de pico para quem precisa sair do campus com mais previsibilidade.",
    tags: ["transporte", "mobilidade", "agendamento"],
  },
  {
    id: "prd-kit-lab",
    sellerId: "gabriela-silva",
    intent: "offer",
    type: "product",
    category: "Laboratorio",
    focus: "Quimica",
    itemCondition: "used",
    negotiationMode: "fixed",
    title: "Kit de laboratorio de Quimica",
    price: 140,
    campus: "Feira de Santana",
    locationNote: "Bloco de laboratorio",
    sellerName: "Gabriela Silva",
    sellerCourse: "Quimica",
    rating: 4.7,
    deliveryMode: "Retirada no bloco de laboratorio",
    featured: false,
    description:
      "Jaleco, oculos, pipetador e itens basicos usados ao longo do semestre.",
    tags: ["quimica", "jaleco", "kit"],
  },
  {
    id: "svc-abnt",
    sellerId: "bianca-almeida",
    intent: "offer",
    type: "service",
    category: "Academico",
    focus: "ABNT",
    negotiationMode: "fixed",
    title: "Revisao ABNT para TCC e artigo",
    price: 90,
    priceUnit: "entrega",
    campus: "Amargosa",
    locationNote: "Online ou biblioteca",
    sellerName: "Bianca Almeida",
    sellerCourse: "Letras",
    rating: 4.8,
    deliveryMode: "Arquivo digital",
    featured: false,
    description:
      "Ajuste fino de formatacao, referencias e organizacao para entregar sem susto.",
    tags: ["abnt", "tcc", "artigo"],
  },
  {
    id: "svc-montagem",
    sellerId: "lucas-santana",
    intent: "offer",
    type: "service",
    category: "Servicos gerais",
    focus: "Montagem",
    negotiationMode: "negotiable",
    title: "Montagem de mesa, prateleira e cadeira",
    price: 60,
    priceUnit: "visita",
    campus: "Cruz das Almas",
    locationNote: "Republicas perto do campus",
    sellerName: "Lucas Santana",
    sellerCourse: "Zootecnia",
    rating: 4.6,
    deliveryMode: "Atendo em republica e apartamento",
    featured: false,
    description:
      "Montagem rapida para quem acabou de se mudar ou cansou de improvisar no quarto.",
    tags: ["republica", "montagem", "ferramenta"],
  },
  {
    id: "prd-violao",
    sellerId: "icaro-menezes",
    intent: "offer",
    type: "product",
    category: "Musica",
    focus: "Iniciante",
    itemCondition: "used",
    negotiationMode: "negotiable",
    title: "Violao Giannini para quem quer recomecar",
    price: 280,
    campus: "Santo Amaro",
    locationNote: "Centro cultural do campus",
    sellerName: "Icaro Menezes",
    sellerCourse: "Artes",
    rating: 4.7,
    deliveryMode: "Retirada no campus",
    featured: false,
    description:
      "Instrumento regulado, capa simples inclusa e som equilibrado para estudo e lazer.",
    tags: ["violao", "arte", "musica"],
  },
  {
    id: "req-percy-jackson",
    sellerId: "aline-moura",
    intent: "request",
    type: "product",
    category: "Livros",
    focus: "Entretenimento",
    itemCondition: "used",
    negotiationMode: "negotiable",
    title: "Procuro colecao Percy Jackson em bom estado",
    price: 45,
    campus: "Cachoeira",
    locationNote: "Biblioteca ou centro",
    sellerName: "Aline Moura",
    sellerCourse: "Jornalismo",
    rating: 4.8,
    deliveryMode: "Entrega combinada no campus",
    featured: false,
    description:
      "Se alguem tiver os volumes principais e quiser vender junto, tenho interesse e aceito negociar.",
    tags: ["demanda", "livros", "fantasia"],
  },
  {
    id: "req-microondas",
    sellerId: "sofia-lima",
    intent: "request",
    type: "product",
    category: "Eletronicos",
    focus: "Cozinha",
    itemCondition: "used",
    negotiationMode: "counter_offer",
    title: "Preciso de um micro-ondas para republica",
    price: 230,
    campus: "Cruz das Almas",
    locationNote: "Residencias universitarias",
    sellerName: "Sofia Lima",
    sellerCourse: "Bacharelado Interdisciplinar em Saude",
    rating: 4.7,
    deliveryMode: "Posso retirar ou combinar entrega local",
    featured: false,
    description:
      "Quero algo funcionando bem e com tamanho medio. Se tiver um modelo parado, manda proposta.",
    tags: ["demanda", "micro-ondas", "republica"],
  },
  {
    id: "req-editor-video",
    sellerId: "daniela-prado",
    intent: "request",
    type: "service",
    category: "Audiovisual",
    focus: "Edicao",
    negotiationMode: "counter_offer",
    title: "Busco edicao de video para projeto de extensao",
    price: 160,
    priceUnit: "projeto",
    campus: "Feira de Santana",
    locationNote: "Projeto remoto",
    sellerName: "Daniela Prado",
    sellerCourse: "Comunicacao",
    rating: 4.8,
    deliveryMode: "Entrega digital com alinhamento por chamada",
    featured: false,
    description:
      "E um video curto para redes e apresentacao institucional. Quero alguem que ja edite com ritmo e legenda.",
    tags: ["demanda", "video", "extensao"],
  },
  {
    id: "req-faxina",
    sellerId: "marcos-vinicius",
    intent: "request",
    type: "service",
    category: "Servicos gerais",
    focus: "Faxina",
    negotiationMode: "counter_offer",
    title: "Procuro faxina leve para apartamento estudantil",
    price: 80,
    priceUnit: "diaria",
    campus: "Santo Antonio de Jesus",
    locationNote: "Apartamento estudantil",
    sellerName: "Marcos Vinicius",
    sellerCourse: "Psicologia",
    rating: 4.6,
    deliveryMode: "Servico presencial em fim de semana",
    featured: false,
    description:
      "Preciso de ajuda com limpeza geral e organizacao basica. Se alguem ja faz esse corre, manda proposta.",
    tags: ["demanda", "faxina", "republica"],
  },
];
